/* JCSQE v7: dependency-free learning logic. Original question IDs are never changed. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.JCSQEStudy=factory();})(typeof window!=='undefined'?window:globalThis,function(){
'use strict';
const VERSION=7,DAY=86400000,KEY='jcsqe-shokyu-state-v3';
const PREFIX=/^(ある業務システム開発で、|レビュー会議において、|運用中のWebサービスについて、|品質保証担当者が判断する場合、|新規プロジェクトで、|保守フェーズにおいて、|テスト計画を作成する際、)/;
const stripRule=x=>String(x||'').replace(/\s+-{3,}\s*$/,'');
const norm=x=>stripRule(x).normalize('NFKC').replace(PREFIX,'').replace(/\s+/g,'').toLowerCase();
const dayKey=(time=Date.now())=>new Date(time+9*3600000).toISOString().slice(0,10);
const daysLeft=(target='2026-11-14',time=Date.now())=>Math.max(0,Math.round((Date.parse(target+'T00:00:00+09:00')-Date.parse(dayKey(time)+'T00:00:00+09:00'))/DAY));
function fingerprint(q){return JSON.stringify([norm(q.text),q.options.map(norm).sort(),norm(q.options[q.correct])]);}
function validateQuestions(qs){const ids=new Set();const errors=[];for(const q of qs){if(!q||typeof q.id!=='string'||ids.has(q.id)||typeof q.text!=='string'||!Array.isArray(q.options)||q.options.length!==4||q.options.some(x=>typeof x!=='string'||!x.trim())||!Number.isInteger(q.correct)||q.correct<0||q.correct>3||!q.explanation)errors.push(q?.id||'missing ID');ids.add(q?.id);}return errors;}
function displayQuestion(q){return /^E\d{2}Q40$/.test(q.id)?{...q,options:q.options.map(stripRule),explanation:stripRule(q.explanation)}:q;}
function catalog(qs){const errors=validateQuestions(qs);if(errors.length)throw Error('問題データが不正です: '+errors.slice(0,4).join(', '));const byId=new Map(),groups=[],byPrint=new Map();for(const source of qs){const q=displayQuestion(source);const key=fingerprint(q);let g=byPrint.get(key);if(!g){g={key:q.id,question:q,ids:[],category:q.category,added:!!q.supplement};byPrint.set(key,g);groups.push(g);}g.ids.push(q.id);byId.set(q.id,g);}return{groups,byId,questions:new Map(qs.map(q=>[q.id,displayQuestion(q)])),rawCount:qs.length};}
function shuffle(a,rng=Math.random){const b=a.slice();for(let i=b.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;}
function cleanObject(v){if(Array.isArray(v))return v.map(cleanObject);if(v&&typeof v==='object'){const out={};for(const [k,x] of Object.entries(v))if(!['__proto__','constructor','prototype'].includes(k))out[k]=cleanObject(x);return out;}return v;}
function normalizeProfile(p={}){return{...p,name:typeof p.name==='string'?p.name.slice(0,50):'ユーザー1',history:Array.isArray(p.history)?p.history:[],sessions:Array.isArray(p.sessions)?p.sessions:[],bookmarks:Array.isArray(p.bookmarks)?p.bookmarks:[],exposures:p.exposures&&typeof p.exposures==='object'?p.exposures:{},activeSession:p.activeSession||null};}
function migrate(raw){const x=cleanObject(raw);if(!x||typeof x!=='object'||!x.profiles||Array.isArray(x.profiles)||typeof x.profiles!=='object')throw Error('保存形式を確認できません。元データを保持しています。');const out={...x,version:VERSION,profiles:{}};for(const [id,p] of Object.entries(x.profiles)){if(p&&typeof p==='object')out.profiles[id]=normalizeProfile(p);}if(!out.profiles[out.activeProfileId])out.activeProfileId=Object.keys(out.profiles)[0]||null;return out;}
function historyByGroup(c,p){const m=new Map();for(const h of p.history){const g=c.byId.get(h.questionId);if(!g||!Number.isFinite(Date.parse(h.timestamp)))continue;if(!m.has(g.key))m.set(g.key,[]);m.get(g.key).push(h);}for(const a of m.values())a.sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp));return m;}
function status(c,p,time=Date.now()){const hist=historyByGroup(c,p);return c.groups.map(g=>{const rows=hist.get(g.key)||[],last=rows.at(-1);let stage=0,lastDay='';for(const h of rows){const d=dayKey(Date.parse(h.timestamp));if(!h.correct||h.confidence!=='sure'){stage=0;lastDay=d;}else if(d!==lastDay){stage++;lastDay=d;}}const interval=[1,3,7,14,21][Math.min(Math.max(stage-1,0),4)];const dueAt=last?Date.parse(last.timestamp)+(last.correct&&last.confidence==='sure'?interval:1)*DAY:0;const exposed=!!p.exposures[g.key];return{...g,rows,last,unseen:!rows.length&&!exposed,due:!!last&&dueAt<=time,dueAt,stage,needs:!!last&&(!last.correct||last.confidence!=='sure')};});}
function balanced(pool,count,rng=Math.random){const buckets=new Map();for(const g of shuffle(pool,rng)){if(!buckets.has(g.category))buckets.set(g.category,[]);buckets.get(g.category).push(g);}const cats=shuffle([...buckets.keys()],rng),out=[];while(out.length<count){let any=false;for(const cat of cats){const g=buckets.get(cat).shift();if(g){out.push(g);any=true;if(out.length===count)break;}}if(!any)break;}return out;}
function select(c,p,mode,count,category,time=Date.now(),rng=Math.random){const all=status(c,p,time);if(mode==='due')return balanced(all.filter(g=>g.due),count,rng);if(mode==='unseen')return balanced(all.filter(g=>g.unseen),count,rng);if(mode==='new'){const pool=all.filter(g=>g.added),fresh=balanced(pool.filter(g=>g.unseen),count,rng),used=new Set(fresh.map(g=>g.key));return [...fresh,...balanced(pool.filter(g=>!used.has(g.key)&&g.due),count-fresh.length,rng),...balanced(pool.filter(g=>!used.has(g.key)&&!g.due),Math.max(0,count-fresh.length-pool.filter(g=>!used.has(g.key)&&g.due).length),rng)].slice(0,count);}if(mode==='bookmarks')return balanced(all.filter(g=>p.bookmarks.includes(g.key)),count,rng);if(mode==='category')return balanced(all.filter(g=>g.category===category),count,rng);if(mode==='mock'||mode==='random')return balanced(all,count,rng);const due=balanced(all.filter(g=>g.due),Math.ceil(count/2),rng);const seen=new Set(due.map(g=>g.key));const fresh=balanced(all.filter(g=>g.unseen&&!seen.has(g.key)),count-due.length,rng);fresh.forEach(g=>seen.add(g.key));return [...due,...fresh,...balanced(all.filter(g=>!seen.has(g.key)),count-due.length-fresh.length,rng)];}
function makeSession(c,p,mode,count,category,time=Date.now(),rng=Math.random){const picked=select(c,p,mode,count,category,time,rng);if(!picked.length)return null;return{id:'s7_'+time+'_'+Math.floor(rng()*1e8),schema:7,kind:mode==='mock'?'mock':'practice',mode,title:mode==='mock'?'時間制限つき演習':mode==='due'?'今日の復習':mode==='new'?'補完問題':mode==='unseen'?'初見チェック':mode==='category'?category+' 演習':mode==='bookmarks'?'あとで復習':'すきま演習',questionIds:picked.map(g=>g.question.id),index:0,answers:{},confidence:{},committed:{},orders:Object.fromEntries(picked.map(g=>[g.question.id,shuffle([0,1,2,3],rng)])),first:Object.fromEntries(picked.map(g=>[g.question.id,g.unseen])),startedAt:time,updatedAt:time,durationSec:3600};}
function adaptSession(s,c,p){if(!s||!Array.isArray(s.questionIds))return null;if(s.questionIds.some(id=>!c.questions.has(id)))return null;if(s.schema===7)return s;const o={...s,schema:7,legacy:true,answers:s.answers||{},confidence:{},committed:{},orders:{},first:{}};for(const id of s.questionIds){o.orders[id]=[0,1,2,3];o.first[id]=false;o.confidence[id]='legacy';if(s.kind==='practice'&&Object.hasOwn(o.answers,id))o.committed[id]=true;}o.index=Math.min(Math.max(Number(o.index)||0,0),o.questionIds.length-1);return o;}
function seenItem(c,p,id,time=Date.now()){const g=c.byId.get(id);if(g&&!p.exposures[g.key])p.exposures[g.key]=time;}
function record(c,p,s,id,time=Date.now()){if(s.committed[id])return false;const q=c.questions.get(id);if(!q)return false;const selected=Number.isInteger(s.answers[id])?s.answers[id]:null;const g=c.byId.get(id);p.history.push({questionId:id,selected,correct:selected===q.correct,timestamp:new Date(time).toISOString(),mode:s.kind,sessionId:s.id,category:q.category,exam:q.exam||null,confidence:s.confidence[id]||'unknown',firstAttempt:s.first[id]===true&&!s.legacy,groupId:g.key,appVersion:7});s.committed[id]=true;seenItem(c,p,id,time);return true;}
function finish(c,p,s,time=Date.now()){for(const id of s.questionIds){if(!Object.hasOwn(s.answers,id)){s.answers[id]=null;s.confidence[id]='unknown';}record(c,p,s,id,time);}const details=s.questionIds.map(id=>{const q=c.questions.get(id),selected=s.answers[id];return{questionId:id,selected,correct:selected===q.correct,confidence:s.confidence[id]||'legacy',firstAttempt:s.first[id]===true&&!s.legacy,order:s.orders[id]};});const correct=details.filter(x=>x.correct).length;const result={id:s.id,title:s.title,kind:s.kind,mode:s.mode,courseCheckpointRound:s.courseCheckpointRound||null,finishedAt:new Date(time).toISOString(),elapsedSec:Math.max(0,Math.floor((time-s.startedAt)/1000)),correct,total:details.length,accuracy:Math.round(correct/details.length*100),details,appVersion:7};if(!p.sessions.some(r=>r.id===result.id))p.sessions.push(result);p.activeSession=null;return result;}
function stats(c,p,time=Date.now()){const all=status(c,p,time),valid=p.history.filter(h=>c.byId.has(h.questionId)),modern=valid.filter(h=>h.appVersion===7);const rate=a=>({total:a.length,correct:a.filter(h=>h.correct).length,accuracy:a.length?Math.round(a.filter(h=>h.correct).length/a.length*100):null});const first=modern.filter(h=>h.firstAttempt),review=modern.filter(h=>!h.firstAttempt);return{total:valid.length,legacy:valid.filter(h=>h.appVersion!==7).length,today:valid.filter(h=>Number.isFinite(Date.parse(h.timestamp))&&dayKey(Date.parse(h.timestamp))===dayKey(time)).length,first:rate(first),review:rate(review),uncertain:modern.filter(h=>h.confidence==='guess').length,unknown:modern.filter(h=>h.confidence==='unknown').length,due:all.filter(g=>g.due).length,unseen:all.filter(g=>g.unseen).length,touched:all.filter(g=>g.rows.length).length,groups:all};}
function importProfile(payload){const data=cleanObject(payload);if(!data||!data.profile||!Array.isArray(data.profile.history))throw Error('JCSQEのプロフィールJSONではありません。');if(data.profile.history.length>100000)throw Error('履歴が多すぎます。');for(const h of data.profile.history)if(!h||typeof h.questionId!=='string'||typeof h.correct!=='boolean'||!Number.isFinite(Date.parse(h.timestamp)))throw Error('履歴の形式が不正です。');const p=normalizeProfile(data.profile);p.name=(p.name+'（復元）').slice(0,50);return p;}
return{VERSION,KEY,DAY,dayKey,daysLeft,norm,fingerprint,validateQuestions,catalog,shuffle,migrate,normalizeProfile,status,select,makeSession,adaptSession,seenItem,record,finish,stats,importProfile};
});
